[tool.poetry]
name = "chicky"
version = "0.1.0"
description = ""
authors = ["Liam"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
automationhat = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
